name: torch113
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli=1.2.0=h27d5ac6_0
  - brotli-bin=1.2.0=h1421c7b_0
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2024.8.30=py38h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cpuonly=2.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9c0eb46_1
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.3=h7354ed3_4
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.51.0=py38h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py38h06a4308_0
  - importlib_resources=6.4.0=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.4.2=py38h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.20.1=h568e23c_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libbrotlicommon=1.2.0=h32cd6e7_0
  - libbrotlidec=1.2.0=ha2c5f68_0
  - libbrotlienc=1.2.0=h2e96acb_0
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=ha637b67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.3=he6710b0_2
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hef93074_0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libpq=12.15=h37d81fd_1
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.7.2=py38h06a4308_0
  - matplotlib-base=3.7.2=py38h1128e8f_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mysql=5.7.24=he378463_2
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.24.3=py38h14f4228_0
  - numpy-base=1.24.3=py38h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=24.1=py38h06a4308_0
  - pcre=8.45=h295c915_0
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - platformdirs=3.10.0=py38h06a4308_0
  - ply=3.11=py38_0
  - pooch=1.7.0=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.10=py38h6a678d5_0
  - pyqt5-sip=12.13.0=py38h5eee18b_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - pytorch=1.13.1=py3.8_cpu_0
  - pytorch-mutex=1.0=cpu
  - qt-main=5.15.2=h110a718_10
  - readline=8.3=hc2a1206_0
  - requests=2.32.3=py38h06a4308_0
  - scikit-learn=1.3.0=py38h1128e8f_1
  - scipy=1.10.1=py38h14f4228_0
  - setuptools=75.1.0=py38h06a4308_0
  - sip=6.7.12=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.51.1=he0a8d7e_0
  - threadpoolctl=3.5.0=py38h2f386ee_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.0.1=py38h06a4308_0
  - torchaudio=0.13.1=py38_cpu
  - torchvision=0.14.1=py38_cpu
  - tornado=6.4.1=py38h5eee18b_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - unicodedata2=15.1.0=py38h5eee18b_0
  - urllib3=2.2.3=py38h06a4308_0
  - wheel=0.44.0=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zipp=3.20.2=py38h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - pandas==2.0.3
      - pytz==2025.2
      - seaborn==0.13.2
      - tzdata==2025.3
prefix: /home/users/ysong30/anaconda3/envs/torch113
